### ISSUE TITLE
Hiba

### ISSUE THREAD

**Issue by Internetezoo** [vmistvan/speech_recog#1]
Üdv!

Windows esetén sklearn hiba. Írja hogy van másik modul, skicit-learn, de ekkor is hiba jön elő

Linuxon Trainer modul hiba van.

**Comment by vmistvan** [comment]
szia! köszi az infót, megírnád a többi modul, de főképp a python verzióját? én 3.11-es pythonnal vitézkedek.

valamint egy gyors próbát megérne az egészet nem lokálban, hanem a google colab oldalán is kirpróbálni..

én - szégyen szemre - először colabban, majd később win alatt csináltam, jóval korábban, csak feldobtam as-is,  de ha fennáll a probléma továbbra is, akkor megnézem újra, egy, a nulláról létrehozott virtuális környezettel is.

**Comment by Internetezoo** [comment]
windows python 3.12
a colabos hiba is megjelent.

most telepítem colabon ami szükéges

colabon python 3.10 van

**Comment by vmistvan** [comment]
Úgy 12GB plussz memóriás videokártya kell amúgy hozzá. Colab ennyit ad.
8kor megnézem gépen, mi van.

**Comment by Internetezoo** [comment]
colabon a hiba:

/usr/local/lib/python3.10/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:34: UnderReviewWarning: The feature generate_power_seq is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  "lr_options": generate_power_seq(LEARNING_RATE_CIFAR, 11),
/usr/local/lib/python3.10/dist-packages/pl_bolts/models/self_supervised/amdim/amdim_module.py:92: UnderReviewWarning: The feature FeatureMapContrastiveTask is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  contrastive_task: Union[FeatureMapContrastiveTask] = FeatureMapContrastiveTask("01, 02, 11"),
/usr/local/lib/python3.10/dist-packages/pl_bolts/losses/self_supervised_learning.py:228: UnderReviewWarning: The feature AmdimNCELoss is currently marked under review. The compatibility with other Lightning projects is not guaranteed and API may change at any time. The API and functionality may change without warning in future releases. More details: https://lightning-bolts.readthedocs.io/en/latest/stability.html
  self.nce_loss = AmdimNCELoss(tclip)
/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py:30: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils as _distutils
2024-09-11 15:50:16.753990: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-11 15:50:16.800528: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-11 15:50:16.812715: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-11 15:50:16.846656: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 15:50:18.768923: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/timm/models/helpers.py:7: DeprecationWarning: Importing from timm.models.helpers is deprecated, please import via timm.models
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", DeprecationWarning)
Traceback (most recent call last):
  File "/content/main_sr_hun_learn.py", line 40, in <module>
    df_hungarian = pd.read_csv(path_txt+'line_index.csv', header=None, delimiter="/", names=['not_required', 'speech_files', 'targets'])
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/Colab Notebooks/line_index.csv'

**Comment by vmistvan** [comment]
oksa, látom.
vagy nem pont ott van a fájl
vagy még nem töltötted fel
ha mégis, akkor első lépés felmountolni.

Tudom, hogy kicsit fura a hibakezelés pythonnál, mert ami a hibához tartozik 14 sorba írva, abból valójában 2 fontos infó van:
I. 40. sorban bukik el,
II. nincs meg a line_index.csv.

közben nekem lefutott a lokális meghajtóra írt változat, de előre szólok, hogy neked nincsenek meg a hangfájlok, mert nem töltöttem fel a szavallatomat emberbaráti okokból.

két lehetőséged van:
- kiszedsz minden tanulást, végülis ez egy elég jól betanított modell már.
- elkészítesz valami hasonlót, és átírod a line_index.csv-t.

mivel ez egy könyv melléklete átdolgozva, az angol anyag is valami alapján készült, azt is csak az eredeti hellyel tudom összelinkelni, nem az enyém. annyi lesz az előny azzal szemben, hogy a könyvben vannak elgépelések.

**Comment by vmistvan** [comment]
Feltettem az angol, de fontosabb, hogy a welsh tájszólást is tartalmazó oldal linkjét. Angol backbone kell hozzá! :)

**Comment by vmistvan** [comment]
a fentiek szerint a hibákat jelenleg két dolog okozta:
1. a python 3.12-es változata a legtöbb AI területen problémás, valami függőség nem teljesül. **a megoldás a 3.11 vagy 3.10-es python használata** (a colab például python 3.10-est használ, és a Pytorch Lightning könyv is azt veszi alapul)
2. nem találta meg a szükséges fájlt. **megoldás: vagy az angol változatot kell használni, és az ahhoz megadott nyelvi adatkészleteket kell használni, vagy elkészíteni egy magyar adatkészletet. a colabon pedig fel kell mountolni,** erről a https://colab.research.google.com/notebooks/io.ipynb oldalon írnak.

holnap, amennyiben nincs ellenvetés, lezárom ezt a hibát.

**Comment by vmistvan** [comment]
a jelzett hibák, és javításuk
1. a python 3.12-es változata a legtöbb AI területen problémás, a függőségek nem teljesülése miatt. **a megoldás a 3.11 vagy 3.10-es python használata** (a colab például python 3.10-est használ, és a Pytorch Lightning könyv is azt veszi alapul)
2. nem találta meg a szükséges fájlt. megoldás: vagy **az angol változatot, és az ahhoz megadott nyelvi adatkészleteket kell használni, vagy elkészíteni egy magyar adatkészletet. a colabon pedig fel kell mountolni**, erről a https://colab.research.google.com/notebooks/io.ipynb oldalon írnak.
Nagyon jó ebben a hibajelentésben, amikor konkrét kimenetet is kaptam, mert azokkal lehet behatárolni a hibát.
